<a href="https://colab.research.google.com/github/learning710/11239A090_DAA_LAB/blob/main/11239A090_exp6b_Flodwarshall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def floyd_warshall(graph):
    num_vertices = len(graph)
    distance = np.full((num_vertices, num_vertices), np.inf)
    for i in range(num_vertices):
        distance[i][i] = 0
    for i in range(num_vertices):
        for j in range(num_vertices):
            if graph[i][j] != 0:
                distance[i][j] = graph[i][j]
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]
    return distance

graph = [
    [0, 1, np.inf],
    [1, 0, 2],
    [np.inf, 2, 0]
]
shortest_paths = floyd_warshall(graph)
print("Shortest path distance matrix:")
print(shortest_paths)

Shortest path distance matrix:
[[0. 1. 3.]
 [1. 0. 2.]
 [3. 2. 0.]]
